config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :rooms do
    collection do
      get "search"
    end
  end
  
  resources :reservations
  get "users/:id/profile" => "users#profile"

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validates  :start_date, presence: true
    validates  :start_date, presence: true
    belongs_to :user
    belongs_to :room


end

app/models/room.rb
class Room < ApplicationRecord
    validates :room_name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true, numericality: true
    validates :adress, presence: true
    validates :room_image, presence: true
    has_one_attached :room_image
    has_one_attached :profile_image
    belongs_to :user
    has_many :reservations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: true
  validates :email, uniqueness: true, presence: true
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :rooms, :dependent => :destroy
  has_many :reservations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller? 
    before_action :set_search

    def set_search
        @q = Room.ransack(params[:q]) 
        @search_rooms = @q.result
      end


    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username]) #サインアップアクション（新規登録）のusernameキーの値を取得
    end



    #def configure_account_update_parameters
     #   devise_parameter_sanitizer.permit(:account_update, keys: [:ここに編集したいカラム])
    #end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :reservation_chk, only: [:new]
  
  def index
    @reservations = Reservation.all
    @rooms = Room.all
  end

  def new
    @reservation = Reservation.new(reservation_params)
    @room = Room.find_by(id: @reservation.room_id)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @room = Room.find_by(id: @reservation.room_id)
    if @reservation.save
      flash[:notice] = "予約が完了しました"
        redirect_to :reservations
    else
      flash[:notice] = "予約に失敗しました"
      redirect_to room_path(@room)
    end
  end


  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "予約済みroomを削除しました"
    redirect_to :reservations
  end


  private

  def reservation_params
    params.require(:reservation).permit(:user_id,:room_id,:start_date, :end_date, :people,  :total_price)
  end

  def reservation_chk
    @reservation = Reservation.new(reservation_params)
    @room = Room.find_by(id: @reservation.room_id)
    
    if  @reservation.start_date == nil && @reservation.end_date == nil
      flash[:notice] = "チェックイン日とチェックアウト日が入力されていません"
        render :"rooms/show"
    elsif 
      @reservation.start_date == nil
        flash[:notice] = "チェックアイン日が入力されていません"
        render :"rooms/show"
      elsif
        @reservation.end_date == nil
          flash[:notice] = "チェックアウト日が入力されていません"
          render :"rooms/show"
        elsif
          @reservation.start_date < Date.today
            flash[:notice] = "今日以降の日付を入力してください"
            render :"rooms/show"
          elsif
            @reservation.end_date <= @reservation.start_date
              flash[:notice] = "チェックアウト日にはチェックイン日より後の日付を入力してください"
              render :"rooms/show"
    end
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :baria_user, only: [:edit, :update, :destroy]
  before_action :login_check, only: [:edit, :update, :destroy,:show,:create]
  
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "ルームを新規登録しました"
      redirect_to :rooms
    else
      render :"new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @user = User.find_by(id: @room.user_id)
    @reservation = Reservation.new
    if @reservation.start_date == nil
      render :"show"
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to :rooms
    else
      render :edit
    end
  end



  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "登録済みroomを削除しました"
    redirect_to :rooms
  end
  

  private

  def room_params
    params.require(:room).permit(:room_name, :introduction, :price, :adress, :room_image)
  end

  def baria_user
    unless Room.find(params[:id]).user.id.to_i == current_user.id
        redirect_to rooms_path(current_user)
    end
  end

  def login_check
    unless user_signed_in? 
      redirect_to new_user_session_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.save
    if current_user.update(user_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to root_path
    else
      render :edit
    end
  end

  def profile
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="top-head">
Potepan Shareでまだ体験したことのない旅をしよう
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p>© 2020 POTEPAN.INC.</p>
</footer>

app/views/layouts/_hedder.html.erb
<header class="header">
    <div class="header-left-nav">
        <div　class="site-name"><%= link_to "booking", root_path, class:"site-name-font" %></div>
        <div class="search-form">
            <%= search_form_for @q, url: search_rooms_path do |f| %>
                <div class="header-sharch d-lg-inline-block d-none">
                    <dt><%= f.text_field :adress_cont , class:"form-control text-position", placeholder: 'エリア' %></dt>
                    <i class="fas fa-map-marker-alt"></i>
                </div>
                <div class="header-sharch"><%= f.submit ("検索") , class:"d-none" %></div>
            <% end %>
        </div>
        <div class="search-form">
            <%= search_form_for @q, url: search_rooms_path do |f| %>
                <div class="header-sharch d-lg-inline-block d-none">
                    <dt><%= f.text_field :introduction_or_room_name_cont , class:"form-control text-position", placeholder: 'キーワード' %></dt>
                    <i class="fas fa-search-plus"></i>
                </div>
                <div class="header-sharch"><%= f.submit ("検索") , class:"d-none" %></div>
            <% end %>
        </div>
    </div>
        <div class="header-right-nav">
            <% if user_signed_in? %> 
                <div class="dropdown nav-item header-nav-menu">
                    <div id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <% if current_user.profile_image.attached? %>
                            <%= image_tag current_user.profile_image, class:"profile-image margin-right" %>
                        <% else %>
                            <%= image_tag "default_user.jpg", class:"profile-image margin-right" %>
                        <% end %>                    
                    </div>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        <button class="dropdown-item" type="button">
                            <%= link_to "ルーム登録", :new_room %>
                        </button>
                        <button class="dropdown-item" type="button">
                            <%= link_to "予約済みルーム", :reservations %>
                        </button>
                        <button class="dropdown-item" type="button">
                            <%= link_to "登録済みルーム", :rooms %>
                        </button>
                        <button class="dropdown-item" type="button">
                            <%= link_to "設定", user_path(current_user.id) %>
                        </button>
                        <button class="dropdown-item" type="button">
                            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                        </button>
                    </div>
                </div>
                <%= current_user.username%>
            <%else %>  
                <%= link_to "登録", new_user_registration_path ,class: 'btn btn-primary' %>
                <%= link_to "ログイン", new_user_session_path ,class: 'btn btn-primary' %>
            <%end %>
        </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <title>BookingSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render "layouts/hedder" %>
  <body>
    <% if flash[:notice] %>  <%# :noticeがあれば表示　%>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
    <%= render "layouts/footer" %>
  </body>

</html>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <% if reservation.user_id == current_user.id %>
          <tr>
            <% @rooms.each do |room| %>
              <% if reservation.room_id == room.id then %>
                <td>
                  <%= link_to image_tag(room.room_image, class: "room-posts-image"), room %>
                </td>
                <td>
                  <%= link_to room.room_name, room %>
                </td>
                <td>
                  <%= room.introduction %>
                </td>
              <% end %>
            <% end %>  
            <td>
              <%= reservation.total_price %>
            </td>
            <td>
              <%= reservation.start_date %>
            </td>
            <td>
              <%= reservation.end_date %>
            </td>
            <td>
              <%= reservation.created_at %>
            </td>
            <td>
              <%= link_to "予約履歴を削除", reservation, method: :delete, class:"btn btn-danger",data: { confirm: "本当に削除しますか？" } %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/new.html.erb
<div class="container reservations-new">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="reservations-new-nav">
                <h4 class="reservations-new-check-content">予約内容確認</h4>
                <h5 class="price-icon">￥<%=@room.price %> / 日</h5>
                <div class="reservations-new-date-select">
                    <% use_of_days = (@reservation.end_date - @reservation.start_date).to_i%> <%# 使用日数＝チェックアウト日ーチェックイン日%>
                    <table>
                        <tr>
                            <div>チェックイン</div>
                            <div class="form-control mb-4"><%= @reservation.start_date %></div>
                        </tr>
                        <tr>
                            <div>チェックアウト</div>
                            <div class="form-control mb-4"><%= @reservation.end_date %></div>
                        </tr>
                        <tr>
                            <div class="reservations-new-check-content">
                                使用日数（チェックイン日 - チェックアウト日）：<b><%= use_of_days %>日</b>
                            </div>
                        </tr>
                        <tr>
                            <div class="reservations-new-check-content">
                                <% if @reservation.people == nil %>
                                    人数：❔人
                                <% else %>
                                    人数：<%= @reservation.people %>人
                                <%end %>
                            </div>
                        </tr>
                        <tr>
                            <div>合計金額</div>
                            <div class="form-control mb-4">¥<%= @reservation.total_price = use_of_days * @room.price %></div>
                            <div>
                                <%= link_to "ルーム詳細に戻る", @room ,class: 'btn btn-secondary form-control' %>
                            </div>
                        </tr>
                    </table>                
                </div>
                <%= form_for @reservation do |f| %>
                    <%= f.hidden_field :user_id %>
                    <%= f.hidden_field :room_id %>
                    <%= f.hidden_field :start_date %>
                    <%= f.hidden_field :end_date %>
                    <%= f.hidden_field :people %>
                    <%= f.hidden_field :total_price, :value => @reservation.total_price %>
                    上記内容でよろしければ「予約を確定」を押してください
                    <%= f.submit '予約を確定する', class:"btn btn-primary form-control" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/rooms/edit.html.erb
<div class="container-fiuld room-posts">
    <h4 class="pb-4">登録済みルーム一覧</h4>
    <table>
        <thead>
            <tr align="center">
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>料金</th>
                <th>住所</th>
            </tr>
        </thead>
        <tbody>
            <tr>    <%# 編集前のroom情報 %>
                <td>
                    <%= image_tag @room.room_image, class:"room-posts-image" %>
                </td>
                <td class="posts-name">
                    <%= @room.room_name %>
                </td>
                <td class="posts-content">
                    <%= @room.introduction %>
                </td>
                <td class="posts-content">
                    <%= @room.price %>
                </td>
                <td class="posts-content">
                    <%= @room.adress %>
                </td>
            </tr>
            <%= form_with model:@room , local: true do |f| %>
                <tr>
                    <td>
                        <%= f.file_field :room_image, class:"room-posts-image" %>
                    </td>
                    <td class="posts-name">
                        <%= f.text_field :room_name %>
                    </td>
                    <td class="posts-content">
                        <%= f.text_area :introduction %>
                    </td>
                    <td class="posts-content">
                        <%= f.number_field :price %>
                    </td>
                    <td class="posts-content">
                        <%= f.text_field :adress %>
                    </td>
                    <td class="posts-content">
                        <%= f.submit "編集を完了する" , class:"btn btn-primary"%>
                    </td>                    
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to "登録ルーム一覧へ戻る", rooms_path%>
</div>       

app/views/rooms/index.html.erb
<div class="container-fiuld room-posts">
    <h4 class="pb-4">登録済みルーム一覧</h4>
    <table>
        <thead>
            <tr align="center">
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>料金</th>
                <th>住所</th>
            </tr>
        </thead>
        <tbody>
            <% room_flg = 0 %>      <%# ログインしているユーザが登録したroomがあるかを判定するフラグ%>
            <% @rooms.each do |room| %>
                <% if room.user_id == current_user.id%>
                    <tr>
                        <td>
                            <%= image_tag room.room_image, class:"room-posts-image" %>
                        </td>
                        <td class="posts-name">
                            <%= link_to room.room_name, room %>
                        </td>
                        <td class="posts-content">
                            <%= room.introduction %>
                        </td>
                        <td class="posts-content">
                            <%= room.price %>
                        </td>
                        <td class="posts-content">
                            <%= room.adress %>
                        </td>
                        <td class="posts-content">
                            <%= link_to "編集", edit_room_path(room.id) , class:"btn btn-primary"%>
                            <%= link_to "削除", room, method: :delete, class:"btn btn-danger",data: { confirm: "本当に削除しますか？" } %>
                        </td>
                        <% room_flg = 1  %> <%# ログインしているユーザが登録したroomが１個でもあればフラグを立てる%>
                    </tr>
                <% end %>
            <% end %>
            <% if room_flg == 0 %>  <%# ログインしているユーザが登録したroomが１個でもあるか判定 %>
                <%= current_user.username %>が登録したroomはありません
            <% end %>
        </tbody>
    </table>
</div>

app/views/rooms/new.html.erb
<article>
    <div class="content ">
        <div class="user-view-box">
            <div class="update-content">
                <b>ルーム情報登録</b>
            </div>
        <%= render "shared/error", obj: @room %>
        <%= form_for @room do |f|%>
            <div class="update-content">
                <div class="row">
                    <label class="col-md-3"><%= f.label :ルーム名 %><p class="badge badge-danger">必須</p></label>
                    <div class="col-md-9">    
                        <%= f.text_field :room_name %>
                    </div>
                </div>
            </div>
            <div class="update-content">
                <div class="row">
                    <label class="col-md-3"><%= f.label :ルーム紹介 %><p class="badge badge-danger">必須</p></label>
                    <div class="col-md-9">    
                        <%= f.text_area :introduction %>
                    </div>
                </div>
            </div>
            <div class="update-content">
                <div class="row">
                    <label class="col-md-3"><%= f.label :料金 %><p class="badge badge-danger">必須</p></label>
                    <div class="col-md-9">    
                        <%= f.number_field :price %>
                    </div>
                </div>
            </div>
            <div class="update-content">
                <div class="row">
                    <label class="col-md-3"><%= f.label :住所 %><p class="badge badge-danger">必須</p></label>
                    <div class="col-md-9">    
                        <%= f.text_field :adress %>
                    </div>
                </div>
            </div>
            <div class="update-content">
                <div class="row">
                    <label class="col-md-3"><%= f.label :ルーム画像 %><p class="badge badge-danger">必須</p></label>
                    <div class="col-md-9">    
                        <%= f.file_field :room_image %>
                    </div>
                </div>
            </div>
            <div class="update-content">                
                <%= f.submit "登録",class: 'btn btn-primary' %>
            </div>
        <%end %>
        </div>
    </div>
</article>

app/views/rooms/search.html.erb
<%count = 0 %>
<% @search_rooms.each do |room| %>
  <% count = count + 1 %>
<% end %>
<h4 class="pb-4 search-result">検索結果：<%= count %>件</h4>

<div class="container-fiuld room">
  <div class="row">
    <% @search_rooms.each do |room| %>
      <div class="col-sm-6 col-lg-4 col-xl-3">
        <div class="room-frame-inner">
          <%= link_to room do %>
            <div class="room-image-out">
              <%= image_tag room.room_image, class:"room-image", alt:"部屋画像" %>
            </div>
            <div class="room-profile">
              <p class="room-profile-name"><%= room.room_name %></p>
              <p class="room-profile-city"><%= room.adress %></p>
              <p class="room-profile-price price-icon">¥<%= room.price %></p>
            </div>
          <% end %>        
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-md-8">
      <%= image_tag @room.room_image, class:"room-show-image"%>
      <div class="room-show-detile">
        <div class="room-show-detile-icon">
          <% if current_user.profile_image.attached? %> <%#ユーザのプロフィール画像が登録されているか❔ %>
            <%= image_tag current_user.profile_image, class:"profile-image margin-right" %>
          <% else %>
            <%= image_tag "default_user.jpg", class:"profile-image margin-right" %>
          <% end %>
        </div>
        <div class="room-show-profile">
          <p class="room-show-profile-name"><%=@room.room_name %></p>
          <p class="room-show-profile-address"><%=@room.adress %></p>
        </div>
      </div>
      <p class="room-show-detile-content"><%=@room.introduction %></p>
    </div>
    <div class="col-md-4">
      <div class="room-show-nav">
        <%= render "shared/error", obj: @reservation %>
        <h5 class="price-icon">¥<%=@room.price %>/ 日</h5>
        <div class="room-show-date-select">
          <%= form_for @reservation, method: :get,  
          url: new_reservation_path(start_date: :start_date, end_date: :end_date,　people: :people,　user_id: :user_id,　room_id: :room_id ) do |f| %> 
          <%#reservationコントローラのnewアクションへ遷移 %>
            <table>
              <tr>
                <th><%= f.label :name ,"チェックイン" %></th>
                <td><%= f.date_field :start_date, class:"form-control mb-4" %></td>
              </tr>
              <tr>
                <th><%= f.label :name ,"チェックアウト" %></th>
                <td><%= f.date_field :end_date ,class:"form-control mb-4"%></td>
              </tr>
              <tr>
                <th><%= f.label :name ,"人数" %></th>
                <td><%= f.number_field :people , class:"form-control mb-4"%></td>
              </tr>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :room_id, :value => @room.id %>
            </table>
            <div>
              <%= f.submit "予約する",class: 'btn btn-primary form-control'%></li>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
        <ul>
        <li><%= message %></li>
        </ul>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |f|%>

<%= f.label :email %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit %>
<%end %>

app/views/users/profile.html.erb
<article>
    <%#  サイドメニューstart *******************************************************************************%>
    <div class="side">
        <div class="side-menu">
            <%= link_to "アカウント", controller: 'users', id: current_user.id, action: 'show' %>
        </div>
        <div class="side-menu">
            <%= link_to "プロフィール", controller: 'users', id: current_user.id, action: 'profile' %>
        </div>
    </div>
    <%#  サイドメニューend *******************************************************************************%>
    <div class="content ">
        <div class="user-view-box">
            <div class="update-content">
                プロフィール
            </div>
            <div class="update-content center">
                <% if @user.profile_image.attached? %>
                    <%= image_tag @user.profile_image, class:"profile-image" %>
                <% else %>
                    <%= image_tag "default_user.jpg", class:"profile-image" %>
                <% end %>
            </div>
            <%= form_for @user do |f|%>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3">
                            <%= f.label :アイコン画像 %>
                        </label>
                        <div class="col-md-9">    
                            <%= f.file_field :profile_image %>
                        </div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3">
                            <%= f.label :ユーザ名 %>
                        </label>
                        <div class="col-md-9">    
                            <%= f.text_field :username %>
                        </div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3">
                            <%= f.label :自己紹介 %>
                        </label>
                        <div class="col-md-9">    
                            <%= f.text_area :profile %>
                        </div>
                    </div>
                </div>
                <div class="update-content">                
                    <%= f.submit "更新",class: 'btn btn-primary' %>
                </div>
            <%end %>
        </div>
    </div>
</article>

app/views/users/show.html.erb
<article>
    <%#  サイドメニューstart *******************************************************************************%>
    <div class="side">
        <div class="side-menu">
            <%= link_to "アカウント", controller: 'users', id: current_user.id, action: 'show' %>
        </div>
        <div class="side-menu">
            <%= link_to "プロフィール", controller: 'users', id: current_user.id, action: 'profile' %>
        </div>
    </div>
    <%#  サイドメニューend *******************************************************************************%>
    <div class="content">
        <div class="user-view-box">
            <div class="update-content">
                アカウント
            </div>
            <div class="update-content">
                <div class="row">
                    <label class="col-md-3">
                        <b>メールアドレス</b>
                    </label>
                    <div class="col-md-9">
                        <%= current_user.email %>
                    </div>
                </div>
            </div>
            <div class="update-content">
                <div class="row">
                    <label class="col-md-3">
                        <b>パスワード</b>
                    </label>
                    <div class="col-md-9">
                        ********
                    </div>
                </div>
            </div>
            <div class="update-content">                
                <%= link_to "編集", edit_user_registration_path ,class: 'btn btn-primary' %>                
            </div>        
        </div>
    </div>
</article>